In [12]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)

In [2]:
pd.__version__

'2.2.2'

In [3]:
df = pd.read_csv('laptops.csv', encoding='ISO-8859-1')
df

Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RAM  Storage Storage type       GPU  \
0     ExpertBook      Intel Core i5    8      512          SSD       NaN   
1             Go      Intel Celeron    8      256          SSD       NaN   
2     ExpertBook      Intel Core i3    8      256          SSD       NaN   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2159        Book  Intel Evo Core i7   16      256          SSD       NaN   

      Screen Touch  Final Price  
0       15.6    No      1009.00  
1       15.6    No       299.00  
2       15.6    No       789.00  
3       15.6    No      1199.00  
4       15.6    No       669.01  
...      ...   ...          ...  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  
2159    13.4   Yes      1699.99  

[2160 rows x 12 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Laptop        2160 non-null   object 
 1   Status        2160 non-null   object 
 2   Brand         2160 non-null   object 
 3   Model         2160 non-null   object 
 4   CPU           2160 non-null   object 
 5   RAM           2160 non-null   int64  
 6   Storage       2160 non-null   int64  
 7   Storage type  2118 non-null   object 
 8   GPU           789 non-null    object 
 9   Screen        2156 non-null   float64
 10  Touch         2160 non-null   object 
 11  Final Price   2160 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 202.6+ KB


### Q2. Records count - How many records are in the dataset?

In [7]:
df.shape[0]

2160

### Q3. Laptop brands - How many laptop brands are presented in the dataset?

In [6]:
df['Brand'].nunique()

27

### Q4. Missing values - How many columns in the dataset have missing values?

In [9]:
df[df.isnull()]

Laptop Status Brand Model  CPU  RAM  Storage Storage type  GPU  Screen  \
0       NaN    NaN   NaN   NaN  NaN  NaN      NaN          NaN  NaN     NaN   
1       NaN    NaN   NaN   NaN  NaN  NaN      NaN          NaN  NaN     NaN   
2       NaN    NaN   NaN   NaN  NaN  NaN      NaN          NaN  NaN     NaN   
3       NaN    NaN   NaN   NaN  NaN  NaN      NaN          NaN  NaN     NaN   
4       NaN    NaN   NaN   NaN  NaN  NaN      NaN          NaN  NaN     NaN   
...     ...    ...   ...   ...  ...  ...      ...          ...  ...     ...   
2155    NaN    NaN   NaN   NaN  NaN  NaN      NaN          NaN  NaN     NaN   
2156    NaN    NaN   NaN   NaN  NaN  NaN      NaN          NaN  NaN     NaN   
2157    NaN    NaN   NaN   NaN  NaN  NaN      NaN          NaN  NaN     NaN   
2158    NaN    NaN   NaN   NaN  NaN  NaN      NaN          NaN  NaN     NaN   
2159    NaN    NaN   NaN   NaN  NaN  NaN      NaN          NaN  NaN     NaN   

     Touch  Final Price  
0      NaN          NaN  
1      NaN          NaN  
2      NaN          NaN  
3      NaN          NaN  
4      NaN          NaN  
...    ...          ...  
2155   NaN          NaN  
2156   NaN          NaN  
2157   NaN          NaN  
2158   NaN          NaN  
2159   NaN          NaN  

[2160 rows x 12 columns]

### Q5. Maximum final price - What's the maximum final price of Dell notebooks in the dataset?

In [11]:
filter_brand = df['Brand'] == 'Dell'
df.loc[filter_brand, 'Final Price'].max()

3936.0

### Q6. Median value of Screen

In [13]:
# Step 1: Find initial median value of the 'Screen' column
screen_median = df['Screen'].median()
print(f"Initial median value of 'Screen': {screen_median}")

Initial median value of 'Screen': 15.6


In [15]:
# Step 2: Find the most frequent value (mode) of the 'Screen' column
most_frequent_value = df['Screen'].mode()[0]
print(f"Most frequent value of 'Screen': {most_frequent_value}")

Most frequent value of 'Screen': 15.6


In [16]:
# Step 3: Fill missing values with the most frequent value
df['Screen'] = df['Screen'].fillna(most_frequent_value)

In [17]:
# Step 4: Calculate the median value after filling missing values
new_median = df['Screen'].median()
print(f"New median value of 'Screen' after filling missing values: {new_median}")

New median value of 'Screen' after filling missing values: 15.6


In [18]:
df['Screen']

0       15.6
1       15.6
2       15.6
3       15.6
4       15.6
        ... 
2155    17.3
2156    17.3
2157    17.3
2158    13.4
2159    13.4
Name: Screen, Length: 2160, dtype: float64

### Q7. Sum of weights

In [19]:
# Step 1: Select all "Innjoo" laptops
innjoo_laptops = df[df['Brand'] == 'Innjoo']
innjoo_laptops

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [22]:
# Step 2: Select only columns RAM, Storage, Screen
X = innjoo_laptops[['RAM', 'Storage', 'Screen']].values  # Convert to numpy array
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [25]:
# Step 3: Compute matrix-matrix multiplication of X.T and X (XTX)
XTX = X.T @ X
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [26]:
# Step 4: Compute the inverse of XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [27]:
# Step 5: Create array y
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [28]:
# Step 6: Multiply XTX_inv with X.T and then with y to get w
w = XTX_inv @ X.T @ y
w

array([45.58076606,  0.42783519, 45.29127938])

In [29]:
# Step 7: Sum all elements of w
sum_w = np.sum(w)
sum_w

91.29988062995496